peca_delivery/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.order_create, name="order_create"),
]

peca_delivery/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path("admin/", admin.site.urls),
    path("cart/", include("peca_delivery.cart.urls", namespace="cart")),
    path("customers/", include("peca_delivery.customers.urls", namespace="customers")),
    path(
        "<slug:store_slug>/orders/",
        include("peca_delivery.orders.urls", namespace="orders"),
    ),
    path(
        "<slug:store_slug>/payment/",
        include("peca_delivery.payment.urls", namespace="payment"),
    ),
    path("<slug:store_slug>/app/", include("peca_delivery.app.urls", namespace="app"),),
    path("paypal/", include("paypal.standard.ipn.urls")),
    # auth
    path("entrar/", LoginView.as_view(), name="sign-in",),
    path("sair/", LogoutView.as_view(), {"next_page": "/"}, name="sign-out"),
    path("", include("peca_delivery.shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if hasattr(settings, "ADMIN_SITE_HEADER"):
    admin.site.site_header = settings.ADMIN_SITE_HEADER
    admin.site.site_title = settings.ADMIN_SITE_HEADER


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

peca_delivery/orders/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from peca_delivery.shop.models import Store, Product, STATE_CHOICES
from peca_delivery.payment.models import PaymentMethod


ORDER_STATUS = (
    (0, _("Verificar")),
    (1, _("Aprovado")),
    (2, _("Trânsito")),
    (3, _("Entregue")),
    (4, _("Recusado")),
)


class Order(models.Model):
    store = models.ForeignKey(
        Store,
        verbose_name=_("Loja"),
        related_name="orders_store",
        on_delete=models.CASCADE,
    )
    first_name = models.CharField(_("Primeiro nome"), max_length=50)
    last_name = models.CharField(_("Último nome"), max_length=50)
    email = models.EmailField(_("Email"))
    address = models.CharField(_("Endereço"), max_length=200)
    address2 = models.CharField(_("Complemento"), max_length=200, blank=True, null=True)
    postal_code = models.CharField(_("CEP"), max_length=20)
    city = models.CharField(_("Cidade"), max_length=100)
    state = models.CharField(_("UF"), max_length=2, choices=STATE_CHOICES, default="PE")
    extra = models.TextField(_("Observações"), blank=True)
    payment = models.ForeignKey(
        PaymentMethod,
        verbose_name=_("Forma de Pagamento"),
        related_name="orders_payment_method",
        on_delete=models.CASCADE,
    )
    change = models.DecimalField(
        _("Troco para"), max_digits=10, decimal_places=2, default=0, blank=True
    )
    no_change = models.BooleanField(
        _("Não preciso de troco"), default=False, blank=True
    )
    status = models.IntegerField(_("Status"), choices=ORDER_STATUS, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    phone = models.CharField(_("Telefone"), max_length=14)
    district = models.CharField(_("Bairro"), max_length=100)
    number = models.IntegerField(_("Número"))

    class Meta:
        ordering = ("created", "status")
        verbose_name = _("Pedido")
        verbose_name_plural = _("Pedidos")
        db_table = "order"

    def __str__(self):
        return "Pedido {}".format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.orders_order_item.all())

    def save(self, *args, **kwargs):
        if self.no_change:
            self.change = 0
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("app:orders", args=[self.store.slug])


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        verbose_name=_("Pedido"),
        related_name="orders_order_item",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        verbose_name=_("Produto"),
        related_name="products_order_item",
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(_("Preço"), max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(_("Quantidade"), default=1)

    class Meta:
        verbose_name = _("Item Pedido")
        verbose_name_plural = _("Itens Pedidos")
        db_table = "order_item"

    def __str__(self):
        return "{}".format(self.id)

    def get_cost(self):
        return self.price * self.quantity

peca_delivery/orders/forms.py
from django import forms

from peca_delivery.payment.models import PaymentMethod

from .models import Order


class OrderCreateForm(forms.ModelForm):
    payment = forms.ModelChoiceField(
        queryset=PaymentMethod.objects.all(),
        empty_label=None,
        widget=forms.RadioSelect(attrs={"class": "custom-control-input"}),
    )
    no_change = forms.BooleanField(
        label="Não preciso de troco",
        initial=False,
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "custom-control-input"}),
    )

    class Meta:
        model = Order
        fields = [
            "first_name",
            "last_name",
            "phone",
            "email",
            "postal_code",
            "address",
            "number",
            "address2",
            "district",
            "city",
            "state",
            "extra",
            "payment",
            "change",
            "no_change",
        ]

peca_delivery/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404

# from django.contrib.auth.decorators import login_required

from peca_delivery.cart.cart import Cart
from peca_delivery.shop.models import Store

from .forms import OrderCreateForm
from .models import OrderItem, Order
from .task import order_created


# @login_required(login_url='/entrar/')
def order_create(request, store_slug):
    cart = Cart(request)
    store = get_object_or_404(Store, slug=store_slug)
    if cart:
        if request.method == "POST":
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                order.store = store
                order = form.save()
                for item in cart:
                    OrderItem.objects.create(
                        order=order,
                        product=item["product"],
                        price=item["price"],
                        quantity=item["quantity"],
                    )
                # clear the cart
                cart.clear()
                order_created(order.id)
                request.session["order_id"] = order.id
                # redirect to the payment
                # TODO: para demostracao modifiquei a finalizacao do
                # pagamento para a tela de done, mas para producao tera
                # que mudar
                # return redirect('payment:process')
                return render(
                    request, "payment/done.html", {"store": store, "order": order.id}
                )

        form = OrderCreateForm()

        context = {
            "cart": cart,
            "form": form,
            "store": store,
        }

        if request.user.is_authenticated:
            email = request.user.email
            # print(request.user)
            last_order = Order.objects.filter(email=email).order_by("-created")[:1]

            if last_order:
                context["order"] = last_order[0]

        return render(request, "orders/order/create.html", context)
    else:
        # TODO: criar uma rotina para quando o carrinho estiver vázio
        return redirect("shop:product_list", store.slug)

peca_delivery/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

{% block title %}
  Checkout
{% endblock %}

{% block header %}
  {% include 'shop/header-soft.html' %}
{% endblock header %}

{% block content %}
  <div class="row">
    <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span>Confira seu pedido</span>
        <span class="badge badge-secondary badge-pill">
          {# call __len__ #}
          {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            {{ total_items }}
          {% else %}
            0
          {% endif %}
          {% endwith %}
        </span>
      </h4>
      <ul class="list-group mb-3">
        {% for item in cart %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ item.product.name }}</h6>
            <small class="text-muted">
              * {{ item.product.unity }}<br>
              x {{ item.quantity }}
            </small>
          </div>
          <span class="text-muted">R$ {{ item.total_price }}</span>
        </li>
        {% endfor %}
        {% comment %} <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Frete</h6>
          </div>
          <span class="text-muted">R$ 5</span>
        </li> {% endcomment %}
        {% comment %} <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Cupom</h6>
            <small>EXAMPLECODE</small>
          </div>
          <span class="text-success">-R$ 5</span>
        </li> {% endcomment %}
        <li class="list-group-item d-flex justify-content-between">
          <span><strong>Total</strong></span>
          <strong>R$ {{ cart.get_total_price }}</strong>
        </li>
      </ul>

      {% comment %} <form class="card p-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Cupom">
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Inserir</button>
          </div>
        </div>
      </form> {% endcomment %}
    </div>

    <!-- FORM -->
    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">Informações do pedido</h4>
      <form action="." method="POST" class="needs-validation" novalidate="">
        {% csrf_token %}
        {% bootstrap_form_errors form type='non_fields' %}
        <div class="row">
          <div class="col-md-6">
            {% bootstrap_field form.first_name placeholder='Primeiro nome' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.last_name placeholder='Último nome' %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            {% bootstrap_field form.phone placeholder='00900009999' %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.email placeholder='nome@email.com' %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            {% bootstrap_field form.postal_code placeholder='55297000' %}
          </div>
          <div class="col-md-9">
            {% bootstrap_field form.address placeholder='Av. Rui Barbosa' %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            {% bootstrap_field form.number placeholder='818' %}
          </div>
          <div class="col-md-9">
            {% bootstrap_field form.address2 placeholder='Apartamento, sala, ponto de referência' %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            {% bootstrap_field form.district %}
          </div>
          <div class="col-md-4">
            {% bootstrap_field form.city %}
          </div>
          <div class="col-md-4">
            {% bootstrap_field form.state %}
          </div>
        </div>
        <div class="mb-3">
          {% bootstrap_field form.extra placeholder='Observações sobre o pedido' %}
        </div>

        {% comment %} <div class="row">
          <div class="col-md-6 mb-3">
            <label for="id_first_name">Primeiro Nome</label>
            <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="" value="{{ request.user.first_name }}" required>
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="id_last_name">Último Nome</label>
            <input type="text" class="form-control" id="id_last_name" placeholder="" value="{{ request.user.first_name }}" required>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="id_email">Email</label>
          <input type="email" class="form-control" id="id_email" placeholder="you@example.com" value="{{ request.user.email }}" required>
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="mb-3">
          <label for="id_address">Endereço</label>
          <input type="text" class="form-control" id="id_address" placeholder="Av. Rui Barbosa, 818" value="" required>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="mb-3">
          <label for="id_address2">Complemento <span class="text-muted">(Optional)</span></label>
          <input type="text" class="form-control" id="id_address2" placeholder="Apartamento, sala, ponto de referência">
        </div>

        <div class="row">
          <div class="col-md-5 mb-3">
            <label for="id_city">Cidade</label>
            <select class="custom-select d-block w-100" id="id_city" required>
              <option value="">Selecione...</option>
              <option value="Garanhuns" selected>Garanhuns</option>
            </select>
            <div class="invalid-feedback">
              Please select a valid country.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="id_state">Estado</label>
            <select class="custom-select d-block w-100" id="id_state" required>
              <option value="">Selecione...</option>
              <option value="PE" selected>Pernambuco</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid state.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="id_zip">CEP</label>
            <input type="text" class="form-control" id="id_zip" placeholder="" required>
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div> {% endcomment %}

        {% comment %} <hr class="mb-4">

        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="save-info" checked>
          <label class="custom-control-label" for="save-info">Salvar essas informações para próxima vez</label>
        </div> {% endcomment %}

        <hr class="mt-4 mb-4">

        <h4 class="mb-3">Forma de pagamento</h4>

        <div id="paymentMethod" class="d-block my-3 mb-4">
          {% for radio in form.payment %}
            <div id="{{ radio.choice_label|lower }}" class="custom-control custom-radio">
              {{ radio.tag }}
              <label class="custom-control-label" for="{{ radio.id_for_label }}">{{ radio.choice_label }}</label>
            </div>
          {% endfor %}

          <div id="change_group" style="display: none">
            <hr class="mt-4 mb-4">

            <div class="row">
              <div class="col-md-6">
                {% bootstrap_field form.change placeholder='0,00' %}
              </div>
              <div class="col-md-6 d-flex align-items-end mb-4">
                <div class="custom-control custom-checkbox">
                  {{ form.no_change }}
                  <label class="custom-control-label" for="{{ form.no_change.id_for_label }}">{{ form.no_change.label }}</label>
                </div>
              </div>
            </div>
          </div>

        </div>

        {% comment %} <div class="row">
          <div class="col-md-6 mb-3">
            <label for="cc-name">Name on card</label>
            <input type="text" class="form-control" id="cc-name" placeholder="" required>
            <small class="text-muted">Full name as displayed on card</small>
            <div class="invalid-feedback">
              Name on card is required
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="cc-number">Credit card number</label>
            <input type="text" class="form-control" id="cc-number" placeholder="" required>
            <div class="invalid-feedback">
              Credit card number is required
            </div>
          </div>
        </div> {% endcomment %}
        {% comment %} <div class="row">
          <div class="col-md-3 mb-3">
            <label for="cc-expiration">Expiration</label>
            <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
            <div class="invalid-feedback">
              Expiration date required
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="cc-expiration">CVV</label>
            <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
            <div class="invalid-feedback">
              Security code required
            </div>
          </div>
        </div> {% endcomment %}

        <hr class="mb-4">

        {% comment %} <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button> {% endcomment %}
        {% bootstrap_button 'Concluir Pedido' button_type='submit' button_class='btn-success' extra_classes='btn-lg btn-block btn-product' size='lg' %}
      </form>
    </div>
  </div>

    {% comment %} <div class="panel panel-primary">
        <div class="panel-heading">Your order</div>
        <div class="panel-body">
            <ul class="list-group">
                {% for item in cart %}
                    <li class="list-group-item">
                        ${{ item.total_price }}
                        <span class="badge">{{ item.product.name }} x{{ item.quantity }}</span>
                    </li>
                {% endfor %}
            </ul>
            <p>Total: ${{ cart.get_total_price }}</p>

        </div>
    </div> {% endcomment %}

    {% comment %} <h1>Checkout</h1>
    <form action="." method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-success btn-product">
          <span class="glyphicon glyphicon-shopping-cart"></span> Place order
        </button>
      {% endbuttons %}
    </form> {% endcomment %}

{% endblock %}

{% block extra_js %}
  {{ block.super }}
  <script>
    $( document ).ready( function() {
      var first_name = $( '#id_first_name' )
      var last_name = $( '#id_last_name' )
      var email = $( '#id_email' )
      var address = $( '#id_address' )
      var address2 = $( '#id_address2' )
      var city = $( '#id_city' )
      var postal_code = $( '#id_postal_code' )

      /*
      if ( !first_name.val() ) {
        first_name.val( "{{ request.user.first_name }}" );
      }
      if ( !last_name.val() ) {
        last_name.val( "{{ request.user.last_name }}" );
      }
      if ( !email.val() ) {
        email.val( "{{ request.user.email }}" );
      }
      */
      {% if order %}
      if ( !first_name.val() ) {
        first_name.val( "{{ order.first_name }}" );
      }
      if ( !last_name.val() ) {
        last_name.val( "{{ order.last_name }}" );
      }
      if ( !email.val() ) {
        email.val( "{{ order.email }}" );
      }
      if ( !address.val() ) {
        address.val( "{{ order.address }}" );
      }
      if ( !address2.val() ) {
        address2.val( "{% if order.address2 %}{{ order.address2 }}{% endif %}" );
      }
      if ( !city.val() ) {
        city.val( "{{ order.city }}" );
      }
      if ( !postal_code.val() ) {
        postal_code.val( "{{ order.postal_code }}" );
      }
      {% endif %}
    });

    $('#paymentMethod').click(function() {
      $('#change_divisor').css('display', 'none');
      $('#change_group').css('display', 'none');
      //$('#Dinheiro').click(function() {
        if($('#dinheiro>input').is(':checked')) {
          $('#change_divisor').css('display', 'block');
          $('#change_group').css('display', 'block');
        }
      //});
    });
  </script>
{% endblock extra_js %}