peca_delivery/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

peca_delivery/shop/urls.py
from django.urls import path

from . import views

app_name = "shop"
urlpatterns = [
    path("", views.store_list, name="store_list"),
    path("<slug:store_slug>/", views.product_list, name="product_list"),
    # path(r'^(?P<store_slug>[-\w]+)/$',
    #     views.product_list,
    #     name='product_list_by_store'),
    path(
        "<slug:store_slug>/<slug:category_slug>/",
        views.product_list,
        name="product_list_by_category",
    ),
    # path(r'^(?P<product_id>\d+)/(?P<slug>[-\w]+)/$',
    #     views.product_detail,
    #     name='product_detail')
]

peca_delivery/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path("admin/", admin.site.urls),
    path("cart/", include("peca_delivery.cart.urls", namespace="cart")),
    path("customers/", include("peca_delivery.customers.urls", namespace="customers")),
    path(
        "<slug:store_slug>/orders/",
        include("peca_delivery.orders.urls", namespace="orders"),
    ),
    path(
        "<slug:store_slug>/payment/",
        include("peca_delivery.payment.urls", namespace="payment"),
    ),
    path("<slug:store_slug>/app/", include("peca_delivery.app.urls", namespace="app"),),
    path("paypal/", include("paypal.standard.ipn.urls")),
    # auth
    path("entrar/", LoginView.as_view(), name="sign-in",),
    path("sair/", LogoutView.as_view(), {"next_page": "/"}, name="sign-out"),
    path("", include("peca_delivery.shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if hasattr(settings, "ADMIN_SITE_HEADER"):
    admin.site.site_header = settings.ADMIN_SITE_HEADER
    admin.site.site_title = settings.ADMIN_SITE_HEADER


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

peca_delivery/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

# from django.core.files import File
# from django.core.files.temp import NamedTemporaryFile

# from urllib.request import urlopen

from peca_delivery.customers.models import Client


STATE_CHOICES = (
    ("AC", "Acre"),
    ("AL", "Alagoas"),
    ("AP", "Amapá"),
    ("AM", "Amazonas"),
    ("BA", "Bahia"),
    ("CE", "Ceará"),
    ("DF", "Distrito Federal"),
    ("ES", "Espírito Santo"),
    ("GO", "Goiás"),
    ("MA", "Maranhão"),
    ("MT", "Mato Grosso"),
    ("MS", "Mato Grosso do Sul"),
    ("MG", "Minas Gerais"),
    ("PA", "Pará"),
    ("PB", "Paraíba"),
    ("PR", "Paraná"),
    ("PE", "Pernambuco"),
    ("PI", "Piauí"),
    ("RJ", "Rio de Janeiro"),
    ("RN", "Rio Grande do Norte"),
    ("RS", "Rio Grande do Sul"),
    ("RO", "Rondônia"),
    ("RR", "Roraima"),
    ("SC", "Santa Catarina"),
    ("SP", "São Paulo"),
    ("SE", "Sergipe"),
    ("TO", "Tocantins"),
)

PRODUCT_STATUS = (
    (0, _("Ativo")),
    (1, _("Em Falta")),
    (2, _("Ocultar")),
)

WEEK_DAY_CHOICES = (
    (0, _("Domingo")),
    (1, _("Segunda")),
    (2, _("Terça")),
    (3, _("Quarta")),
    (4, _("Quinta")),
    (5, _("Sexta")),
    (6, _("Sabádo")),
)

UNITY_CHOICES = (
    ("AMPOLA", _("AMPOLA")),
    ("BALDE", _("BALDE")),
    ("BANDEJ", _("BANDEJA")),
    ("BARRA", _("BARRA")),
    ("BISNAG", _("BISNAGA")),
    ("BLOCO", _("BLOCO")),
    ("BOBINA", _("BOBINA")),
    ("BOMB", _("BOMBONA")),
    ("CAPS", _("CAPSULA")),
    ("CART", _("CARTELA")),
    ("CENTO", _("CENTO")),
    ("CJ", _("CONJUNTO")),
    ("CM", _("CENTIMETRO")),
    ("CM2", _("CENTIMETRO QUADRADO")),
    ("CX", _("CAIXA")),
    ("CX2", _("CAIXA COM 2 UNIDADES")),
    ("CX3", _("CAIXA COM 3 UNIDADES")),
    ("CX5", _("CAIXA COM 5 UNIDADES")),
    ("CX10", _("CAIXA COM 10 UNIDADES")),
    ("CX15", _("CAIXA COM 15 UNIDADES")),
    ("CX20", _("CAIXA COM 20 UNIDADES")),
    ("CX25", _("CAIXA COM 25 UNIDADES")),
    ("CX50", _("CAIXA COM 50 UNIDADES")),
    ("CX100", _("CAIXA COM 100 UNIDADES")),
    ("DISP", _("DISPLAY")),
    ("DUZIA", _("DUZIA")),
    ("EMBAL", _("EMBALAGEM")),
    ("FARDO", _("FARDO")),
    ("FOLHA", _("FOLHA")),
    ("FRASCO", _("FRASCO")),
    ("GALAO", _("GALÃO")),
    ("GF", _("GARRAFA")),
    ("GRAMAS", _("GRAMAS")),
    ("JOGO", _("JOGO")),
    ("KG", _("QUILOGRAMA")),
    ("KIT", _("KIT")),
    ("LATA", _("LATA")),
    ("LITRO", _("LITRO")),
    ("M", _("METRO")),
    ("M2", _("METRO QUADRADO")),
    ("M3", _("METRO CÚBICO")),
    ("MILHEI", _("MILHEIRO")),
    ("ML", _("MILILITRO")),
    ("MWH", _("MEGAWATT HORA")),
    ("PACOTE", _("PACOTE")),
    ("PALETE", _("PALETE")),
    ("PARES", _("PARES")),
    ("PC", _("PEÇA")),
    ("POTE", _("POTE")),
    ("K", _("QUILATE")),
    ("RESMA", _("RESMA")),
    ("ROLO", _("ROLO")),
    ("SACO", _("SACO")),
    ("SACOLA", _("SACOLA")),
    ("TAMBOR", _("TAMBOR")),
    ("TANQUE", _("TANQUE")),
    ("TON", _("TONELADA")),
    ("TUBO", _("TUBO")),
    ("UNID", _("UNIDADE")),
    ("VASIL", _("VASILHAME")),
    ("VIDRO", _("VIDRO")),
)


class Store(models.Model):
    client = models.ForeignKey(
        Client, verbose_name=_("Cliente"), on_delete=models.CASCADE, null=True,
    )
    logo = models.ImageField(_("Logo"), upload_to="shop/stores", blank=False)
    name = models.CharField(_("Nome da Loja"), max_length=100, db_index=True)
    slug = models.SlugField(_("URL"), max_length=100, db_index=True, unique=True)
    phone = models.CharField(_("Fone"), max_length=20)
    address = models.CharField(_("Endereço"), max_length=200)
    address2 = models.CharField(_("Complemento"), max_length=200, blank=True, null=True)
    postal_code = models.CharField(_("CEP"), max_length=20)
    city = models.CharField(_("Cidade"), max_length=100)
    state = models.CharField(_("UF"), max_length=2, choices=STATE_CHOICES, default="PE")
    extra = models.TextField(_("Informações Extras"),)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tax = models.DecimalField(
        _("Taxa de Entrega"), default=0, max_digits=10, decimal_places=2
    )
    delivery_time = models.CharField(
        _("Tempo de Espera"), max_length=20, blank=True, null=True
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = _("Loja")
        verbose_name_plural = _("Lojas")
        index_together = (("id", "slug"),)
        db_table = "store"

    def __str__(self):
        return ("{} ({})").format(self.name, self.slug)

    def get_absolute_url(self):
        return reverse("shop:product_list", args=[self.slug])


class Category(models.Model):
    store = models.ForeignKey(
        Store,
        verbose_name=_("Loja"),
        related_name="categories_store",
        on_delete=models.CASCADE,
    )
    name = models.CharField(_("Nome"), max_length=200, db_index=True)
    slug = models.SlugField(_("URL"), max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name = _("Categoria")
        verbose_name_plural = _("Categorias")
        db_table = "category"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            "shop:product_list_by_category", args=[self.store.slug, self.slug]
        )


class Product(models.Model):
    store = models.ForeignKey(
        Store,
        verbose_name=_("Loja"),
        related_name="products_store",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        verbose_name=_("Categoria"),
        related_name="products_category",
        on_delete=models.CASCADE,
    )
    name = models.CharField(_("Nome"), max_length=200, db_index=True)
    slug = models.SlugField(_("URL"), max_length=200, db_index=True)
    image = models.ImageField(_("Foto"), upload_to="shop/products", blank=True)
    image_url = models.URLField(_("Endereço da Foto"), blank=True)
    description = models.TextField(_("Descrição"), blank=True)
    price = models.DecimalField(_("Preço"), max_digits=10, decimal_places=2)
    status = models.BooleanField(_("Status"), default=0, choices=PRODUCT_STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    unity = models.CharField(
        _("Unidade de Medida"), max_length=20, choices=UNITY_CHOICES, default="UNID"
    )

    class Meta:
        ordering = ["category", "name"]
        verbose_name = _("Produto")
        verbose_name_plural = _("Produtos")
        index_together = (("id", "slug"),)
        db_table = "product"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])

    def admin_image(self):
        if self.image:
            return format_html('<img src="{}" height="50" />'.format(self.image.url))
        elif self.image_url:
            return format_html('<img src="{}" height="50" />'.format(self.image_url))
        else:
            return "{}".format(_("Sem imagem"))

    admin_image.allow_tags = True
    admin_image.short_description = _("Imagem")

    # def save(self, *args, **kwargs):
    #     if self.image_url:
    #         img_temp = NamedTemporaryFile(delete=True)
    #         img_temp.write(urlopen(self.image_url).read())
    #         img_temp.flush()

    #         self.image.save(self.image, File(img_temp))


class Banner(models.Model):
    store = models.ForeignKey(
        Store,
        verbose_name=_("Loja"),
        related_name="banners_store",
        on_delete=models.CASCADE,
    )
    image = models.ImageField(_("Imagem"), upload_to="banners/%Y/%m/%d")
    title = models.CharField(_("Título"), max_length=100, blank=True)
    body = models.CharField(_("Texto do banner"), max_length=200, blank=True)
    button = models.CharField(_("Texto do botão"), max_length=20, blank=True)

    class Meta:
        ordering = ["title"]
        verbose_name = _("Banner")
        verbose_name_plural = _("Banners")
        db_table = "banner"

    def __str__(self):
        return self.image.url

    def admin_image(self):
        try:
            return format_html('<img src="{}" height="50" />'.format(self.image.url))
        except:
            return "{}".format(_("Sem imagem"))

    admin_image.allow_tags = True
    admin_image.short_description = _("Imagem")


class Schedule(models.Model):
    store = models.ForeignKey(
        Store,
        verbose_name=_("Loja"),
        related_name="schedules_store",
        on_delete=models.CASCADE,
    )
    day = models.IntegerField(_("Dia"), choices=WEEK_DAY_CHOICES)
    first_hour_start = models.TimeField(_("Primeiro Horário (Início)"), blank=True)
    first_hour_end = models.TimeField(_("Primeiro Horário (Fim)"), blank=True)
    second_hour_start = models.TimeField(_("Segundo Horário (Início)"), blank=True)
    second_hour_end = models.TimeField(_("Segundo Horário (Fim)"), blank=True)
    third_hour_start = models.TimeField(_("Terceiro Horário (Início)"), blank=True)
    third_hour_end = models.TimeField(_("Terceiro Horário (Fim)"), blank=True)

    class Meta:
        ordering = ["day"]
        verbose_name = _("Horário de Funcionamento")
        verbose_name_plural = _("Horários de Funcionamento")
        db_table = "schedule"

    def __str__(self):
        return ("{}: {}").format(self.store, self.get_day_display())

    def display_day_hour(self):
        hours = ""

        first_start = self.first_hour_start
        first_end = self.first_hour_end
        second_start = self.second_hour_start
        second_end = self.second_hour_end
        third_start = self.third_hour_start
        third_end = self.third_hour_end

        if first_start and first_end:
            hours = hours + ("{0} até {1}").format(first_start, first_end)

peca_delivery/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db import connection
from django.core.paginator import Paginator

from peca_delivery.customers.models import Client
from peca_delivery.cart.cart import Cart
from peca_delivery.cart.forms import CartAddProductFormHidden

from .decorators import is_public
from .models import Store, Category, Product, Banner


@is_public
def store_list(request):
    client = get_object_or_404(Client, schema_name=connection.schema_name)

    stores = Store.objects.all()
    context = {"client": client, "stores": stores}

    if len(stores) > 1:
        return render(request, "shop/store/list.html", context)

    if stores:
        return redirect("shop:product_list", stores[0].slug)


@is_public
def product_list(request, store_slug=None, category_slug=None):
    category = None
    store = get_object_or_404(Store, slug=store_slug)
    search = request.GET.get("search")

    # remove car session how much store change
    cart = Cart(request)
    for x in cart:
        if not x["store"] == store.id:
            for key in list(request.session.keys()):
                del request.session[key]

    categories = Category.objects.filter(store=store.id)
    banners = Banner.objects.filter(store=store.id)

    if search:
        products = Product.objects.filter(
            store=store.id, status=0, name__icontains=search
        )
    else:
        products = Product.objects.filter(store=store.id, status=0)

    if category_slug:
        category = get_object_or_404(Category, store=store.id, slug=category_slug)
        products = products.filter(store=store.id, category=category)

    # pagination
    paginator = Paginator(products, 50)
    page = request.GET.get("page")
    products = paginator.get_page(page)

    cart_product_form = CartAddProductFormHidden()

    return render(
        request,
        "shop/product/list.html",
        {
            "store": store,
            "category": category,
            "categories": categories,
            "products": products,
            "banners": banners,
            "cart_product_form": cart_product_form,
        },
    )


# detalhes do produto desativado
# para ativar precisa finalizar o codigo
# def product_detail(request, product_id, slug):
#     product = get_object_or_404(Product,
#                                 id=product_id,
#                                 slug=slug,
#                                 status=0)
#     cart_product_form = CartAddProductForm()
#     return render(request,
#                   'shop/product/detail.html',
#                   {'product': product,
#                    'cart_product_form': cart_product_form})

peca_delivery/shop/templates/shop/base.html
{% load static bootstrap4 %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% bootstrap_css %}
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  </head>

  <body class="bg-light">
    <!-- As a link -->
    {% block header %}
    {% endblock header %}

    <main role="main">
      {% block banner %}
      {% endblock banner %}

      <div class="py-5">
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>

    {% comment %} <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading">
          {# call __len__ #}
          {% with total_items=cart|length %}
            {% if cart|length > 0 %}
              Your cart:
              <a href="{% url "cart:cart_detail" %}">
                {# If total_items is 1, the output will be 1 item. #}
                {# If total_items is 2, the output will be 2 items. #}
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
              </a>
            {% else %}
              Your shopping cart is empty.
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </div> {% endcomment %}

    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'assets/js/ajax-csrf.js' %}"></script>
    {% bootstrap_javascript %}

    <script>
      feather.replace()
    </script>

    {% block extra_js %}
    {% endblock extra_js %}

  </body>
</html>

peca_delivery/shop/templates/shop/header-shop.html
{% load static bootstrap4 %}

<!-- web -->
<div class="container absolute-top no-mobile">
  <div class="media bg-white p-3 rounded-bottom box-shadow">
    <img class="mr-3" src="{{ store.logo.url }}" alt="Logo" height="130">
    <div class="media-body">
      <h2 class="mt-0">
        <b>{{ store.name }}</b>
        <small class="pull-right">
          <i class="fa fa-whatsapp"></i>
          <a href="https://wa.me/55{{ store.phone }}" class="text-dark" target="_blank">
            {{ store.phone }}
          </a>
        </small>
      </h2>
      <p>{{ store.address }}, {% if store.address2 %}{{ store.address2}}, {% endif %}{{ store.city }}-{{ store.state }}</p>
      <div class="row">
        {% if store.delivery_time %}
        <div class="col-md-4">
          <small class="text-muted">Tempo de espera</small>
          <p>{{ store.delivery_time }}</p>
        </div>
        {% endif %}
        <div class="col-md-4">
          <small class="text-muted">Taxa de entrega</small>
          <p>{% if store.tax %}R$ {{ store.tax }}{% else %}Grátis{% endif %}</p>
        </div>
        <!-- <div class="col-md-4"> -->
        <!--   <!-1- <small class="text-muted">Aberto <i class="fa fa-circle text-success"></i></small> -1-> -->
        <!--   <small class="text-muted">Funcionamento</small> -->
        <!--   <p>07:00 às 19:00</p> -->
        <!-- </div> -->
      </div>
    </div>
  </div>

  <nav class="navbar navbar-expand-md navbar-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="dropdown-toggle btn btn-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="" data-feather="user"></i>
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'sign-out' %}?next={{request.path}}">Sair</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="btn btn-light" href="{% url 'sign-in' %}?next={{request.path}}">Entrar</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

<!-- mobile --> 
<div class="absolute-top text-center mobile">
  <div class="bg-white col-12 p-3 ">
    <h2 class="mt-0">
      <b>{{ store.name }}</b>
    </h2>
    <p class="mb-1">
      {{ store.address }}, {% if store.address2 %}{{ store.address2}}, {% endif %}{{ store.city }}-{{ store.state }}
      <br>
      <i class="fa fa-whatsapp"></i>
      <a href="https://wa.me/55{{ store.phone }}" class="text-dark" target="_blank">
        {{ store.phone }}
      </a>
    </p>
    <!-- <p class="mb-1 text-muted"><i class="fa fa-circle text-success"></i> Aberto <i class="fa fa-chevron-down"></i></p> -->
    <div class="row mb-4">
      {% if store.delivery_time %}
      <div class="col-6">
        <small class="text-muted">Tempo de espera</small>
        <p>{{ store.delivery_time }}</p>
      </div>
      {% endif %}
      <div class="col-6">
        <small class="text-muted">Taxa de entrega</small>
        <p>{% if store.tax %}R$ {{ store.tax }}{% else %}Grátis{% endif %}</p>
      </div>
    </div>
  </div>

  <div class="d-flex bd-highlight">
    <div class="ml-auto p-2 bd-highlight">
      {% if user.is_authenticated %}
      <div class="dropdown">
        {% comment %} dropdown-toggle {% endcomment %}
        <button class="btn btn-light"
          type="button" id="dropdownMenuButton" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="" data-feather="user"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'sign-out' %}">Sair</a>
        </div>
      </div>
      {% else %}
        <a class="btn btn-light" href="{% url 'sign-in' %}" role="button">Entrar</a>
      {% endif %}
    </div>
  </div>
  <img class="bg-white p-2 rounded" src="{{ store.logo.url }}" alt="Logo" height="100">

</div>

peca_delivery/shop/templates/shop/header-soft.html
{% load static bootstrap4 %}

<nav class="navbar navbar-expand-md navbar-light bg-white rounded-bottom shadow">
  <div class="container">
    <a class="navbar-brand" href="{% url 'shop:product_list' store.slug %}">
      <img class="mr-3 rounded" src="{{ store.logo.url }}" alt="Logo" height="50">
      {% comment %} <b>Empório Gamboa</b> {% endcomment %}
    </a>
    {% comment %} <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Produtos</a>
      </li>
    </ul> {% endcomment %}

    {% comment %} {% if user.is_authenticated %}
    Olá, {% if user.first_name %}{{ user.get_full_name }}{% else %}{{ user.username }}{% endif %}.
    {% endif %} {% endcomment %}

    {% comment %} <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> {% endcomment %}

    {% comment %} <div class="collapse navbar-collapse" id="navbarsExampleDefault"> {% endcomment %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'sign-out' %}?next={{request.path}}">
            <i data-feather="user"></i>
            {{ user.username }}
          </a>
          {% else %}
          <a class="nav-link" href="{% url 'sign-in' %}?next={{request.path}}">
            <i data-feather="user"></i>
            Faça login ou cadastre-se
          </a>
          {% endif %}
        </li>
        {% comment %} {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="btn btn-secondary dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i data-feather="user"></i>
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'sign-out' %}">Sair</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="btn btn-success" href="{% url 'sign-in' %}">Faça login ou cadastre-se</a>
        </li>
        {% endif %} {% endcomment %}
      </ul>
    {% comment %} </div> {% endcomment %}
  </div>
</nav>





{% comment %} <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav> {% endcomment %}