peca_delivery/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

peca_delivery/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.order_create, name="order_create"),
]

peca_delivery/shop/urls.py
from django.urls import path

from . import views

app_name = "shop"
urlpatterns = [
    path("", views.store_list, name="store_list"),
    path("<slug:store_slug>/", views.product_list, name="product_list"),
    # path(r'^(?P<store_slug>[-\w]+)/$',
    #     views.product_list,
    #     name='product_list_by_store'),
    path(
        "<slug:store_slug>/<slug:category_slug>/",
        views.product_list,
        name="product_list_by_category",
    ),
    # path(r'^(?P<product_id>\d+)/(?P<slug>[-\w]+)/$',
    #     views.product_detail,
    #     name='product_detail')
]

peca_delivery/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path("admin/", admin.site.urls),
    path("cart/", include("peca_delivery.cart.urls", namespace="cart")),
    path("customers/", include("peca_delivery.customers.urls", namespace="customers")),
    path(
        "<slug:store_slug>/orders/",
        include("peca_delivery.orders.urls", namespace="orders"),
    ),
    path(
        "<slug:store_slug>/payment/",
        include("peca_delivery.payment.urls", namespace="payment"),
    ),
    path("<slug:store_slug>/app/", include("peca_delivery.app.urls", namespace="app"),),
    path("paypal/", include("paypal.standard.ipn.urls")),
    # auth
    path("entrar/", LoginView.as_view(), name="sign-in",),
    path("sair/", LogoutView.as_view(), {"next_page": "/"}, name="sign-out"),
    path("", include("peca_delivery.shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if hasattr(settings, "ADMIN_SITE_HEADER"):
    admin.site.site_header = settings.ADMIN_SITE_HEADER
    admin.site.site_title = settings.ADMIN_SITE_HEADER


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

peca_delivery/cart/models.py
from django.db import models

# Create your models here.

peca_delivery/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class CartAddProductFormHidden(forms.Form):
    quantity = forms.IntegerField(widget=forms.HiddenInput(attrs={"value": 1}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

peca_delivery/cart/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST

from peca_delivery.shop.models import Product

from .cart import Cart
from .forms import CartAddProductForm


# @require_POST
# def cart_add(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     form = CartAddProductForm(request.POST)
#     if form.is_valid():
#         cd = form.cleaned_data
#         cart.add(product=product,
#                  quantity=cd['quantity'],
#                  update_quantity=cd['update'])
#     return redirect('cart:cart_detail')


@require_POST
def cart_add(request, product_id):
    if request.method == "POST":
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            c_data = form.cleaned_data
            cart.add(
                product=product,
                quantity=c_data["quantity"],
                update_quantity=c_data["update"],
            )

            product_id = str(product.id)
            data = {}
            data["product_id"] = product.id
            data["product_name"] = product.name
            data["product_unity"] = product.unity
            data["quantity"] = cart.cart[product_id]["quantity"]
            data["price"] = cart.cart[product_id]["price"]

            total_price = cart.get_total_price()
            data["total_price"] = str(total_price)

            total_items = cart.__len__()
            data["total_items"] = str(total_items)

            # return HttpResponse(data, content_type="application/json")
            return HttpResponse(json.dumps(data), content_type="application/json")

    return HttpResponse(
        json.dumps({"status": "error"}), content_type="application/json"
    )


def cart_remove(request, product_id):
    if request.method == "GET":
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        data = {}
        data["product_id"] = product_id

        total_price = cart.get_total_price()
        data["total_price"] = str(total_price)

        total_items = cart.__len__()
        data["total_items"] = str(total_items)

        return HttpResponse(json.dumps(data), content_type="application/json")

    return HttpResponse(
        json.dumps({"status": "error"}), content_type="application/json"
    )
    # return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "update": True}
        )
    return render(request, "cart/detail.html", {"cart": cart})

peca_delivery/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static bootstrap3 %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Your shopping cart</h1>

    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Total</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td class="col-sm-8 col-md-6">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="{{ product.get_absolute_url }}">
                                        <img class="media-object"
                                             src="{% if product.image %}{{ product.image.url }}
                                                  {% else %}{% static "img/no_image.png" %}{% endif %}"
                                             style="width: 72px; height: 72px;">
                                    </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a
                                                href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                                        <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-1 col-md-1" style="text-align: center">
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {% bootstrap_field item.update_quantity_form.quantity show_label=False %}
                                    {% bootstrap_field item.update_quantity_form.update %}
                                    {% buttons %}
                                        <button type="submit" class="btn btn-success btn-product">
                                            Update
                                        </button>
                                    {% endbuttons %}
                                </form>
                            </td>

                            <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.price }}</strong></td>
                            <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.total_price }}</strong></td>

                            <td class="col-sm-1 col-md-1">
                                <a href="{% url "cart:cart_remove" product.id %}" class="btn btn-danger">
                                    <i class="glyphicon glyphicon-remove" aria-hidden="true"></i> Remove
                                </a>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h3>Total</h3></td>
                    <td class="text-right"><h3><strong>${{ cart.get_total_price }}</strong></h3></td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td>
                        <a href="{% url 'shop:product_list' %}" class="btn btn-default">
                            Continue Shopping <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url "orders:order_create" %}" class="btn btn-default">Checkout <i
                                class="glyphicon glyphicon-play" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}