peca_delivery/app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path("", views.orders, name="orders"),
    path("<int:order_pk>/", views.orders, name="order_items"),
    path("<int:order_pk>/action/", views.order_action, name="order_action"),
    path("<int:order_pk>/accept/", views.order_action, name="order_accept"),
    path("<int:order_pk>/reject/", views.order_action, name="order_reject"),
    path("<int:order_pk>/transit/", views.order_action, name="order_transit"),
    path("<int:order_pk>/delivered/", views.order_action, name="order_delivered"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

peca_delivery/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

peca_delivery/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.order_create, name="order_create"),
]

peca_delivery/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path("admin/", admin.site.urls),
    path("cart/", include("peca_delivery.cart.urls", namespace="cart")),
    path("customers/", include("peca_delivery.customers.urls", namespace="customers")),
    path(
        "<slug:store_slug>/orders/",
        include("peca_delivery.orders.urls", namespace="orders"),
    ),
    path(
        "<slug:store_slug>/payment/",
        include("peca_delivery.payment.urls", namespace="payment"),
    ),
    path("<slug:store_slug>/app/", include("peca_delivery.app.urls", namespace="app"),),
    path("paypal/", include("paypal.standard.ipn.urls")),
    # auth
    path("entrar/", LoginView.as_view(), name="sign-in",),
    path("sair/", LogoutView.as_view(), {"next_page": "/"}, name="sign-out"),
    path("", include("peca_delivery.shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if hasattr(settings, "ADMIN_SITE_HEADER"):
    admin.site.site_header = settings.ADMIN_SITE_HEADER
    admin.site.site_title = settings.ADMIN_SITE_HEADER


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

peca_delivery/orders/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from peca_delivery.shop.models import Store, Product, STATE_CHOICES
from peca_delivery.payment.models import PaymentMethod


ORDER_STATUS = (
    (0, _("Verificar")),
    (1, _("Aprovado")),
    (2, _("Trânsito")),
    (3, _("Entregue")),
    (4, _("Recusado")),
)


class Order(models.Model):
    store = models.ForeignKey(
        Store,
        verbose_name=_("Loja"),
        related_name="orders_store",
        on_delete=models.CASCADE,
    )
    first_name = models.CharField(_("Primeiro nome"), max_length=50)
    last_name = models.CharField(_("Último nome"), max_length=50)
    email = models.EmailField(_("Email"))
    address = models.CharField(_("Endereço"), max_length=200)
    address2 = models.CharField(_("Complemento"), max_length=200, blank=True, null=True)
    postal_code = models.CharField(_("CEP"), max_length=20)
    city = models.CharField(_("Cidade"), max_length=100)
    state = models.CharField(_("UF"), max_length=2, choices=STATE_CHOICES, default="PE")
    extra = models.TextField(_("Observações"), blank=True)
    payment = models.ForeignKey(
        PaymentMethod,
        verbose_name=_("Forma de Pagamento"),
        related_name="orders_payment_method",
        on_delete=models.CASCADE,
    )
    change = models.DecimalField(
        _("Troco para"), max_digits=10, decimal_places=2, default=0, blank=True
    )
    no_change = models.BooleanField(
        _("Não preciso de troco"), default=False, blank=True
    )
    status = models.IntegerField(_("Status"), choices=ORDER_STATUS, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    phone = models.CharField(_("Telefone"), max_length=14)
    district = models.CharField(_("Bairro"), max_length=100)
    number = models.IntegerField(_("Número"))

    class Meta:
        ordering = ("created", "status")
        verbose_name = _("Pedido")
        verbose_name_plural = _("Pedidos")
        db_table = "order"

    def __str__(self):
        return "Pedido {}".format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.orders_order_item.all())

    def save(self, *args, **kwargs):
        if self.no_change:
            self.change = 0
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("app:orders", args=[self.store.slug])


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        verbose_name=_("Pedido"),
        related_name="orders_order_item",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        verbose_name=_("Produto"),
        related_name="products_order_item",
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(_("Preço"), max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(_("Quantidade"), default=1)

    class Meta:
        verbose_name = _("Item Pedido")
        verbose_name_plural = _("Itens Pedidos")
        db_table = "order_item"

    def __str__(self):
        return "{}".format(self.id)

    def get_cost(self):
        return self.price * self.quantity

peca_delivery/orders/forms.py
from django import forms

from peca_delivery.payment.models import PaymentMethod

from .models import Order


class OrderCreateForm(forms.ModelForm):
    payment = forms.ModelChoiceField(
        queryset=PaymentMethod.objects.all(),
        empty_label=None,
        widget=forms.RadioSelect(attrs={"class": "custom-control-input"}),
    )
    no_change = forms.BooleanField(
        label="Não preciso de troco",
        initial=False,
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "custom-control-input"}),
    )

    class Meta:
        model = Order
        fields = [
            "first_name",
            "last_name",
            "phone",
            "email",
            "postal_code",
            "address",
            "number",
            "address2",
            "district",
            "city",
            "state",
            "extra",
            "payment",
            "change",
            "no_change",
        ]

peca_delivery/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404

# from django.contrib.auth.decorators import login_required

from peca_delivery.cart.cart import Cart
from peca_delivery.shop.models import Store

from .forms import OrderCreateForm
from .models import OrderItem, Order
from .task import order_created


# @login_required(login_url='/entrar/')
def order_create(request, store_slug):
    cart = Cart(request)
    store = get_object_or_404(Store, slug=store_slug)
    if cart:
        if request.method == "POST":
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                order.store = store
                order = form.save()
                for item in cart:
                    OrderItem.objects.create(
                        order=order,
                        product=item["product"],
                        price=item["price"],
                        quantity=item["quantity"],
                    )
                # clear the cart
                cart.clear()
                order_created(order.id)
                request.session["order_id"] = order.id
                # redirect to the payment
                # TODO: para demostracao modifiquei a finalizacao do
                # pagamento para a tela de done, mas para producao tera
                # que mudar
                # return redirect('payment:process')
                return render(
                    request, "payment/done.html", {"store": store, "order": order.id}
                )

        form = OrderCreateForm()

        context = {
            "cart": cart,
            "form": form,
            "store": store,
        }

        if request.user.is_authenticated:
            email = request.user.email
            # print(request.user)
            last_order = Order.objects.filter(email=email).order_by("-created")[:1]

            if last_order:
                context["order"] = last_order[0]

        return render(request, "orders/order/create.html", context)
    else:
        # TODO: criar uma rotina para quando o carrinho estiver vázio
        return redirect("shop:product_list", store.slug)

peca_delivery/app/templates/app/menu.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link {% block orders_active %}{% endblock %}" href="{% url 'app:orders' %}">
          <span data-feather="download"></span>
          Pedidos {% block orders_current %}{% endblock %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% block meals_active %}{% endblock %}" href="#">
          <span data-feather="book-open"></span>
          Cardápio {% block meals_current %}{% endblock %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% block dashboard_active %}{% endblock %}" href="{% url 'app:dashboard' %}">
          <span data-feather="bar-chart-2"></span>
          Estatística {% block dashboard_current %}{% endblock %}
        </a>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Administrar</span>
      {% comment %} <a class="d-flex align-items-center text-muted" href="#">
        <span data-feather="plus-circle"></span>
      </a> {% endcomment %}
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="settings"></span>
          Dados da Empresa
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="clock"></span>
          Horário de Entrega
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="map"></span>
          Área de Entrega
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="credit-card"></span>
          Pagamento na Entrega
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="dollar-sign"></span>
          Pagamento Online
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="check-square"></span>
          Pesquisa de Satisfação
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="users"></span>
          Usuários
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="printer"></span>
          Impressoras
        </a>
      </li>
    </ul>
  </div>
</nav>

peca_delivery/app/templates/app/orders-list.html
{% block orders_list %}
<ul class="list-group mb-3 box-shadow">
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h5 class="text-muted mt-2"><b>{{ orders|length }}&numsp;</b> PEDIDOS EM ABERTO</h5>
    </div>
    {% comment %} <span class="text-muted feather-24 mt-2" data-feather="phone"></span> {% endcomment %}
  </li>
  {% for item in orders %}
  <li class="list-group-item d-flex justify-content-between lh-condensed box-clickble{% if order.pk == item.pk %} active{% endif %}" data-url="{% url 'app:order_items' store.slug item.pk %}">
    <div class="container row">
      <div class="col-md-3">
        <h6 class="my-0">#{{ item.pk }}</h6>
        <small>{{ item.created|date:"H:i" }}</small>
      </div>
      <div class="col-md-9">
        <h6 class="my-0">{{ item.first_name }} {{ item.last_name }}</h6>
        <small>R$ {{ item.get_total_cost }}</small>
      </div>
    </div>
    <span id="status-list_{{ item.pk }}" class="text-uppercase font-weight-bold {% if item.status == 0 %}text-danger{% elif item.status == 1 %}text-success{% elif item.status == 2 %}text-info{% elif item.status == 3 %}text-primary{% elif item.status == 4 %}text-secondary{% endif %}">
      {{ item.get_status_display }}
    </span>
  </li>
  {% endfor %}
  {% comment %} <li class="list-group-item d-flex justify-content-between lh-condensed box-clickble" data-url="#">
    <div class="container row">
      <div class="col-md-3">
        <h6 class="my-0">#1202</h6>
        <small>10:12</small>
      </div>
      <div class="col-md-9">
        <h6 class="my-0">Nome da Pessoa</h6>
        <small>R$ 60,00</small>
      </div>
    </div>
    <span class="text-success text-uppercase"><b>Aprovado</b></span>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed box-clickble" data-url="#">
    <div class="container row">
      <div class="col-md-3">
        <h6 class="my-0">#1201</h6>
        <small>10:12</small>
      </div>
      <div class="col-md-9">
        <h6 class="my-0">Nome da Pessoa</h6>
        <small>R$ 15,00</small>
      </div>
    </div>
    <span class="text-primary text-uppercase"><b>Entregue</b></span>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed box-clickble" data-url="#">
    <div class="container row">
      <div class="col-md-3">
        <h6 class="my-0">#1200</h6>
        <small>11:01</small>
      </div>
      <div class="col-md-9">
        <h6 class="my-0">Nome da Pessoa</h6>
        <small>R$ 45,00</small>
      </div>
    </div>
    <span class="text-primary text-uppercase"><b>Entregue</b></span>
  </li> {% endcomment %}
</ul>
{% endblock orders_list %}

peca_delivery/app/templates/app/orders.html
{% extends "app/base.html" %}

{% load static bootstrap4 %}

{% block orders_active %} active{% endblock orders_active %}

{% block orders_current %}<span class="sr-only">(current)</span>{% endblock orders_current %}

{% block main %}
<!-- <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Pedidos</h1>
</div> -->

<div class="row pt-3 mt-3">
  <div class="col-md-5 mb-4">
    {% block orders_list %}
      {% include 'app/orders-list.html' %}
    {% endblock orders_list %}
  </div>
  <div class="col-md-7">
    <div class="card bg-white mb-5 box-shadow border">
      <div class="card-body">
        {% if order.pk > 0 %}
        <h5>
          Pedido #{{ order.pk }}&numsp;
          <small id="status-order_{{ order.pk }}" class="text-uppercase font-weight-bold {% if order.status == 0 %}text-danger{% elif order.status == 1 %}text-success{% elif order.status == 2 %}text-info{% elif order.status == 3 %}text-primary{% elif order.status == 4 %}text-secondary{% endif %}">
            {{ order.get_status_display }}
          </small>
        </h5>
        {% comment %} # TODO: Mudar o method das actions para POST {% endcomment %}
        {% comment %} <form action="{% url 'cart:cart_add' product.id %}" method="POST" id="form-add-cart"> {% endcomment %}
        <button id="acceptOrder_{{ order.pk }}" type="submit" class="btn btn-success btn-rounded px-5 py-2 text-uppercase mb-3 mr-3 font-weight-bold" style="display: none">
          Aceitar
        </button>
        {% comment %} </form> {% endcomment %}
        <button id="rejectOrder_{{ order.pk }}" type="submit" class="btn btn-outline-secondary btn-rounded px-5 py-2 text-uppercase mb-3 font-weight-bold" style="display: none">
          Recusar
        </button>
        <button id="transitOrder_{{ order.pk }}" type="submit" class="btn btn-info btn-rounded px-5 py-2 text-uppercase mb-3 font-weight-bold" style="display: none">
          Marcar como em trânsito
        </button>
        <button id="deliveredOrder_{{ order.pk }}" type="submit" class="btn btn-primary btn-rounded px-5 py-2 text-uppercase mb-3 font-weight-bold" style="display: none">
          Marcar como entregue
        </button>
        <div class="row">
          <div class="col-sm-8">
            <span class="text-muted">Cliente:</span> {{ order.first_name }} {{ order.last_name }}
          </div>
          <div class="col-sm-4 text-right">
            {{ order.created|date:"d/m/Y H:i" }}
          </div>
        </div>
        <div class="row">
          <div class="col-sm-8">
            <span class="text-muted">Endereço:</span> {{ order.address }}{% if order.address2 %}, {{ order.address2 }}{% endif %}
          </div>
          <div class="col-sm-4 text-right">
            {% comment %} <a href="#" class="text-uppercase">Detalhes</a> {% endcomment %}
          </div>
        </div>

        <div class="table-responsive border rounded my-3">
          <table class="table table-note m-0">
            <thead>
              <tr>
                <th>Qtd.</th>
                <th>Item</th>
                <th class="text-right">Preço</th>
              </tr>
            </thead>
            <tbody>
              {% for item in order.orders_order_item.all %}
              <tr>
                <td>{{ item.quantity }}</td>
                <td>{{ item.product }}</td>
                <td class="text-right">R$ {{ item.get_cost }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="row">
          <div class="col-sm-8">
            <span class="text-muted">Forma de pagamento:</span> {{ order.payment }}
            <br>
            {% if order.payment|lower == 'dinheiro' %}
            <span class="text-muted">Valor do troco:</span> {% if order.no_change %}Sem troco{% else %}{{ order.change }}{% endif %}
            {% endif %}
          </div>
          <div class="col-sm-4 text-right">
            <span class="text-muted">Total:</span>
            <span class="total">R$ {{ order.get_total_cost }}</span>
          </div>
        </div>
        {% else %}
        <h5>
          Selecione um pedido.
        </h5>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock main %}

{% block js_bottom %}
{{ block.super }}
<script>
  $(".box-clickble").click(function() {
    window.location = $(this).attr("data-url");
    return false;
  });

  $( document ).ready( function() {
    {% if order.status == 0 %}
      //Verificar
      $('#acceptOrder_{{ order.pk }}').css('display', 'inline');
      $('#rejectOrder_{{ order.pk }}').css('display', 'inline');
      $('#transitOrder_{{ order.pk }}').css('display', 'none');
      $('#deliveredOrder_{{ order.pk }}').css('display', 'none');
    {% elif order.status == 1 %}
      //Aprovado
      $('#acceptOrder_{{ order.pk }}').css('display', 'none');
      $('#rejectOrder_{{ order.pk }}').css('display', 'none');
      $('#transitOrder_{{ order.pk }}').css('display', 'inline');
      $('#deliveredOrder_{{ order.pk }}').css('display', 'none');
    {% elif order.status == 2 %}
      //Trânsito
      $('#acceptOrder_{{ order.pk }}').css('display', 'none');
      $('#rejectOrder_{{ order.pk }}').css('display', 'none');
      $('#transitOrder_{{ order.pk }}').css('display', 'none');
      $('#deliveredOrder_{{ order.pk }}').css('display', 'inline');
    {% else %}
      //Entregue e Recusado
      $('#acceptOrder_{{ order.pk }}').css('display', 'none');
      $('#rejectOrder_{{ order.pk }}').css('display', 'none');
      $('#transitOrder_{{ order.pk }}').css('display', 'none');
      $('#deliveredOrder_{{ order.pk }}').css('display', 'none');
    {% endif %}
  });

  // Accept element
  $('#acceptOrder_{{ order.pk }}').click(function(event){
    event.preventDefault();
    order_action('{{ order.pk }}', 'accept');
  });

  // Reject element
  $('#rejectOrder_{{ order.pk }}').click(function(event){
    event.preventDefault();
    order_action('{{ order.pk }}', 'reject');
  });

  // Transit element
  $('#transitOrder_{{ order.pk }}').click(function(event){
    event.preventDefault();
    order_action('{{ order.pk }}', 'transit');
  });

  // Delivered element
  $('#deliveredOrder_{{ order.pk }}').click(function(event){
    event.preventDefault();
    order_action('{{ order.pk }}', 'delivered');
  });

  function order_action(id, action) {
    $.ajax({
      url: "{% url 'app:order_action' store.slug order.pk %}?a=" + action,
      method: 'GET',
      success: function (data) {
        if (action == 'accept') {
          $('#status-list_{{ order.pk }}').removeClass('text-danger');
          $('#status-list_{{ order.pk }}').addClass('text-success');
          $('#status-list_{{ order.pk }}').text('Aprovado');
          $('#status-order_{{ order.pk }}').removeClass('text-danger');
          $('#status-order_{{ order.pk }}').addClass('text-success');
          $('#status-order_{{ order.pk }}').text('Aprovado');
          $('#acceptOrder_{{ order.pk }}').css('display', 'none');
          $('#rejectOrder_{{ order.pk }}').css('display', 'none');
          $('#transitOrder_{{ order.pk }}').css('display', 'inline');
          $('#deliveredOrder_{{ order.pk }}').css('display', 'none');
        } else if (action == 'transit') {
          $('#status-list_{{ order.pk }}').removeClass('text-success');
          $('#status-list_{{ order.pk }}').addClass('text-info');
          $('#status-list_{{ order.pk }}').text('Trânsito');
          $('#status-order_{{ order.pk }}').removeClass('text-success');
          $('#status-order_{{ order.pk }}').addClass('text-info');
          $('#status-order_{{ order.pk }}').text('Trânsito');
          $('#acceptOrder_{{ order.pk }}').css('display', 'none');
          $('#rejectOrder_{{ order.pk }}').css('display', 'none');
          $('#transitOrder_{{ order.pk }}').css('display', 'none');
          $('#deliveredOrder_{{ order.pk }}').css('display', 'inline');
        } else if (action == 'delivered') {
          $('#status-list_{{ order.pk }}').removeClass('text-info');
          $('#status-list_{{ order.pk }}').addClass('text-primary');
          $('#status-list_{{ order.pk }}').text('Entregue');
          $('#status-order_{{ order.pk }}').removeClass('text-info');
          $('#status-order_{{ order.pk }}').addClass('text-primary');
          $('#status-order_{{ order.pk }}').text('Entregue');
          $('#acceptOrder_{{ order.pk }}').css('display', 'none');
          $('#rejectOrder_{{ order.pk }}').css('display', 'none');
          $('#transitOrder_{{ order.pk }}').css('display', 'none');
          $('#deliveredOrder_{{ order.pk }}').css('display', 'none');
        } else {
          //reject
          $('#status-list_{{ order.pk }}').removeClass('text-danger');
          $('#status-list_{{ order.pk }}').addClass('text-secondary');
          $('#status-list_{{ order.pk }}').text('Recusado');
          $('#status-order_{{ order.pk }}').removeClass('text-danger');
          $('#status-order_{{ order.pk }}').addClass('text-secondary');
          $('#status-order_{{ order.pk }}').text('Recusado');
          $('#acceptOrder_{{ order.pk }}').css('display', 'none');
          $('#rejectOrder_{{ order.pk }}').css('display', 'none');
          $('#transitOrder_{{ order.pk }}').css('display', 'none');
          $('#deliveredOrder_{{ order.pk }}').css('display', 'none');
        }
        console.log(action);
        //console.log("Transit");
      },
      // handle a non-successful response
      error: function (xhr, errmsg, err) {
        alert("Oops! Nós encontramos um erro: " + errmsg); // add the error to the dom
        //console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
      }
    });
    return false;
  };
</script>
{% endblock js_bottom %}

peca_delivery/app/templates/app/pagination.html
{% if page_obj %}

  <nav aria-label="Page navigation" class="pt-5">
    <ul class="pagination justify-content-center">

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link text-success" href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Anterior</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Anterior</a>
        </li>
      {% endif %}

      {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item">
          <a class="page-link text-success" href="?page={{ page_obj.number|add:'-5' }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">&hellip;</a>
        </li>
      {% endif %}

      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <a class="page-link bg-success" href="#" style="border-color: #28a745;">{{ i }}</a>
          </li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
          <li class="page-item">
            <a class="page-link text-success" href="?page={{ i }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
        <li class="page-item">
          <a class="page-link text-success" href="?page={{ page_obj.number|add:'5' }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">&hellip;</a>
        </li>
      {% endif %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link text-success" href="?page={{ page_obj.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Próxima</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Próxima</a>
        </li>
      {% endif %}

    </ul>
  </nav>

{% endif %}